-- TIMEBANK EDU POSTGRESQL PRE-MIGRATION BACKUP DUMP
-- Exported at: 2026-10-08T23:59:25.189840
-- Total Tables: 13

-- Data for table: ai_logs (46 rows)
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (1, 3, 'dan_y_buoi_hoc', 'Soạn dàn ý buổi học Toán Hình học 12', 'Đã sinh cấu trúc 3 phần: Lý thuyết định nghĩa, bài tập mẫu và mẹo giải nhanh.', '2026-09-28 13:50:00');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (2, 4, 'dan_y_buoi_hoc', 'Soạn dàn ý hướng dẫn đệm đàn Guitar', 'Đã sinh danh sách hợp âm C, Am, Dm, G7 và bài tập bấm gam.', '2026-09-29 15:10:00');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (3, 5, 'kiem_duyet', 'Kiểm duyệt nội dung chia sẻ kỹ năng tiếng Anh', 'Nội dung giáo dục an toàn, tích cực, không vi phạm chuẩn mực sư phạm.', '2026-10-01 10:00:00');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (4, 3, 'goi_y_nhiem_vu', 'Gợi ý nhiệm vụ cộng đồng phù hợp học sinh', 'Đã đề xuất nhiệm vụ hỗ trợ số hóa sách thư viện dựa trên kỹ năng tin học.', '2026-10-05 08:30:00');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (5, 3, 'tro_ly_ao', 'Tư vấn lộ trình trao đổi kỹ năng học đường', 'Trợ lý ảo đã giải đáp thắc mắc về quy chế tín dụng thời gian cho học sinh.', '2026-10-05 09:15:00');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (6, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (7, 3, 'goi_y_ghep_cap', 'Môn: Ngoại ngữ, Trình độ: Cần củng cố, Rảnh: Chiều thứ 3, sáng thứ 7, Số ứng viên: 1', '[Rule-Based] 1 gia sư được chọn', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (8, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (9, 1, 'canh_bao', 'Học sinh ngưng học: 1, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (10, 1, 'canh_bao', 'Học sinh ngưng học: 1, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (11, 1, 'canh_bao', 'Học sinh ngưng học: 1, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (12, 1, 'canh_bao', 'Học sinh ngưng học: 1, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (13, 1, 'canh_bao', 'Học sinh ngưng học: 1, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (14, 1, 'canh_bao', 'Học sinh ngưng học: 1, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 13:46:26');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (15, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 23:54:10');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (16, 3, 'goi_y_ghep_cap', 'Môn: Ngoại ngữ, Trình độ: Cần củng cố, Rảnh: Chiều thứ 3, sáng thứ 7, Số ứng viên: 1', '[Rule-Based] 1 gia sư được chọn', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (17, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (18, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (19, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (20, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (21, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (22, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (23, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:11');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (24, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 23:54:16');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (25, 3, 'goi_y_ghep_cap', 'Môn: Ngoại ngữ, Trình độ: Cần củng cố, Rảnh: Chiều thứ 3, sáng thứ 7, Số ứng viên: 1', '[Rule-Based] 1 gia sư được chọn', '2026-10-08 23:54:16');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (26, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 23:54:16');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (27, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:16');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (28, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:16');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (29, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:17');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (30, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:17');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (31, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:17');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (32, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:17');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (33, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (34, 3, 'goi_y_ghep_cap', 'Môn: Ngoại ngữ, Trình độ: Cần củng cố, Rảnh: Chiều thứ 3, sáng thứ 7, Số ứng viên: 1', '[Rule-Based] 1 gia sư được chọn', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (35, 3, 'tom_tat_phan_hoi', 'Tổng 2 đánh giá của user #3', '[Rule-Based] Tóm tắt phản hồi học sinh', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (36, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (37, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (38, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (39, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (40, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:21');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (41, 1, 'canh_bao', 'Học sinh ngưng học: 2, Cặp đôi xung đột: 0', '[Rule-Based] Cảnh báo sớm quản trị học đường', '2026-10-08 23:54:22');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (42, 1, 'tro_ly_ao', '[Quản trị viên Hệ thống] Hỏi: Xin chào bạn, tôi muốn hỏi số dư', '[Rule-Based] Chào Quản trị viên Hệ thống! Hiện tại số dư tín dụng học tập trong ví của bạn là 100.0 giờ. Bạn có thể dùng số giờ này để đặt lịch học kỹ năng mới cùng bạn bè trên Chợ kỹ năng nhé!', '2026-10-08 23:54:28');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (43, 1, 'tro_ly_ao', '[Quản trị viên Hệ thống] Hỏi: Chào bạn', 'Chào bạn! Tôi là trợ lý AI học đường của TimeBank EDU, rất vui được hỗ trợ bạn hôm nay.', '2026-10-08 23:54:28');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (44, 1, 'tro_ly_ao', '[Quản trị viên Hệ thống] Hỏi: Xin chào bạn, tôi muốn hỏi số dư', '[Rule-Based] Chào Quản trị viên Hệ thống! Hiện tại số dư tín dụng học tập trong ví của bạn là 100.0 giờ. Bạn có thể dùng số giờ này để đặt lịch học kỹ năng mới cùng bạn bè trên Chợ kỹ năng nhé!', '2026-10-08 23:54:46');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (45, 1, 'tro_ly_ao', '[Quản trị viên Hệ thống] Hỏi: Bạn có thể giới thiệu về TimeBank không?', '[Rule-Based] Chào Quản trị viên Hệ thống! Tôi là Trợ lý Học đường TimeBank EDU (Hỗ trợ bởi AI Gemini). Số dư ví hiện tại của bạn là 100.0h. Bạn có thể hỏi tôi về: số dư giờ, lịch học sắp tới, hướng dẫn đăng kỹ năng hoặc gợi ý lộ trình học tập!', '2026-10-08 23:54:48');
INSERT INTO ai_logs (id, user_id, chuc_nang, input_tom_tat, output_text, thoi_gian) VALUES (46, 1, 'tro_ly_ao', '[Quản trị viên Hệ thống] Hỏi: Chào bạn', 'Chào bạn! Tôi là trợ lý AI học đường của TimeBank EDU, rất vui được hỗ trợ bạn hôm nay.', '2026-10-08 23:54:48');

-- Data for table: blog_posts (1 rows)
INSERT INTO blog_posts (id, tieu_de, noi_dung, anh_minh_hoa, tac_gia_ai, trang_thai, thoi_gian_dang) VALUES (1, 'Khởi động Mô hình Ngân hàng Thời gian Học đường: Một giờ bạn dạy - Một giờ bạn học', 'Chào mừng toàn thể Thầy Cô giáo và các bạn học sinh đến với TimeBank EDU! Tại đây, mọi tri thức đều bình đẳng, 1 giờ dạy đổi lấy 1 giờ học. Hãy cùng nhau chia sẻ thế mạnh và giúp đỡ bạn bè cùng tiến bộ nhé!', '/static/img/newsletter_banner.svg', 0, 'da_dang', '2026-10-01 08:00:00');

-- Data for table: chat_messages (2 rows)
INSERT INTO chat_messages (id, user_id, vai_tro, noi_dung, thoi_gian) VALUES (1, 3, 'user', 'Em muốn học thêm kỹ năng giao tiếp tiếng Anh thì nên tìm bạn nào?', '2026-10-01 09:00:00');
INSERT INTO chat_messages (id, user_id, vai_tro, noi_dung, thoi_gian) VALUES (2, 3, 'assistant', 'Chào An! Dựa trên hệ thống, bạn Lê Kim Chi (10A3) đang chia sẻ kỹ năng Luyện phản xạ IELTS Speaking rất phù hợp với em nhé!', '2026-10-01 09:00:05');

-- Data for table: community_tasks (4 rows)
INSERT INTO community_tasks (id, tieu_de, mo_ta, dia_diem, so_gio_thuong, so_luong_toi_da, han_dang_ky, nguoi_tao_id, trang_thai, thoi_gian_tao) VALUES (1, 'Dọn rác bãi biển Hạ Long sáng Chủ nhật', 'Hoạt động thanh niên tình nguyện thu gom rác thải nhựa tại bờ biển, làm sạch cảnh quan môi trường.', 'Bãi tắm Bãi Cháy, TP. Hạ Long', 2.0, 10, '2026-10-25', 2, 'mo_dang_ky', '2026-10-05 08:00:00');
INSERT INTO community_tasks (id, tieu_de, mo_ta, dia_diem, so_gio_thuong, so_luong_toi_da, han_dang_ky, nguoi_tao_id, trang_thai, thoi_gian_tao) VALUES (2, 'Hỗ trợ thư viện trường sắp xếp sách', 'Phân loại sách giáo khoa mới, dán mã định danh và sắp xếp lên giá sách theo chuẩn thư viện xanh.', 'Phòng Thư viện - Tầng 2', 1.5, 5, '2026-10-20', 2, 'mo_dang_ky', '2026-10-05 08:30:00');
INSERT INTO community_tasks (id, tieu_de, mo_ta, dia_diem, so_gio_thuong, so_luong_toi_da, han_dang_ky, nguoi_tao_id, trang_thai, thoi_gian_tao) VALUES (3, 'Dạy kỹ năng số cho các em khối Tiểu học', 'Phụ đạo tin học, hướng dẫn các em học sinh lớp 3-4 gõ bàn phím 10 ngón và tra cứu tài liệu học tập an toàn.', 'Phòng máy Tin học số 2', 2.0, 4, '2026-10-30', 2, 'mo_dang_ky', '2026-10-05 09:00:00');
INSERT INTO community_tasks (id, tieu_de, mo_ta, dia_diem, so_gio_thuong, so_luong_toi_da, han_dang_ky, nguoi_tao_id, trang_thai, thoi_gian_tao) VALUES (4, 'Hỗ trợ số hóa tài liệu thư viện trường', 'Quét và phân loại sách tham khảo vào hệ thống thư viện điện tử.', 'Phòng Thư viện - Tầng 2', 2.0, 4, '2026-10-15', 2, 'hoan_thanh', '2026-10-04 08:00:00');

-- Data for table: credits_ledger (11 rows)
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (1, 3, 1.0, 'Dạy Toán cho Trần Thanh Bình', 1, '2026-09-28 15:00:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (2, 4, -1.0, 'Học Toán từ Nguyễn Hoàng An', 1, '2026-09-28 15:00:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (3, 4, 1.0, 'Dạy Đàn cho Lê Kim Chi', 2, '2026-09-29 16:30:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (4, 5, -1.0, 'Học Đàn từ Trần Thanh Bình', 2, '2026-09-29 16:30:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (5, 5, 1.0, 'Dạy Tiếng Anh cho Nguyễn Hoàng An', 3, '2026-10-01 17:00:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (6, 3, -1.0, 'Học Tiếng Anh từ Lê Kim Chi', 3, '2026-10-01 17:00:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (7, 3, 1.0, 'Dạy Toán cho Phạm Quang Minh', 4, '2026-10-03 10:00:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (8, 6, -1.0, 'Học Toán từ Nguyễn Hoàng An', 4, '2026-10-03 10:00:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (9, 6, 1.0, 'Dạy Python cho Vũ Thu Hà', 5, '2026-10-04 15:30:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (10, 7, -1.0, 'Học Python từ Phạm Quang Minh', 5, '2026-10-04 15:30:00');
INSERT INTO credits_ledger (id, user_id, bien_dong, ly_do, session_id, thoi_gian) VALUES (11, 3, 2.0, 'nhiem_vu_cong_dong: Hỗ trợ số hóa tài liệu thư viện', NULL, '2026-10-05 11:00:00');

-- Data for table: quiz_questions (15 rows)
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (1, 1, 'Khái niệm góc giữa hai mặt phẳng trong không gian được đo bằng góc giữa:', 'Hai đường thẳng bất kỳ trên hai mặt phẳng', 'Hai đường thẳng lần lượt vuông góc với giao tuyến tại cùng một điểm', 'Hai vectơ chỉ phương ngẫu nhiên', 'Giao tuyến của hai mặt phẳng', 'B');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (2, 1, 'Khi hai mặt phẳng vuông góc với nhau, góc giữa chúng bằng bao nhiêu độ?', '0 độ', '45 độ', '90 độ', '180 độ', 'C');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (3, 1, 'Để tính khoảng cách từ một điểm M đến mặt phẳng (P), ta cần dựng:', 'Đoạn vuông góc kẻ từ M đến mặt phẳng (P)', 'Một đường thẳng xiên bất kỳ', 'Đường thẳng song song với (P)', 'Đoạn nối M với trọng tâm tam giác đáy', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (4, 1, 'Cho hình chóp S.ABC có SA vuông góc với đáy (ABC). Góc giữa đường thẳng SB và đáy là:', 'Góc SBA', 'Góc SAB', 'Góc ASB', 'Góc SCB', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (5, 1, 'Tuyệt chiêu nhận diện nhanh góc giữa mặt bên và mặt đáy trong hình chóp đều là gì?', 'Xác định trung điểm cạnh đáy rồi nối với đỉnh', 'Kẻ bừa một đường thẳng nối tâm đáy', 'Không thể xác định', 'Dùng thước đo độ trên giấy', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (6, 2, 'Hợp âm Đô trưởng (C) cơ bản gồm những nốt nào trong âm giai?', 'Đô - Mi - Son (C - E - G)', 'Đô - Rê - Mi (C - D - E)', 'La - Đô - Mi (A - C - E)', 'Son - Si - Rê (G - B - D)', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (7, 2, 'Khi bấm hợp âm La thứ (Am), ngón trỏ thường đặt ở vị trí nào?', 'Ngăn 1 dây 2 (nốt Đô)', 'Ngăn 2 dây 3', 'Ngăn 3 dây 1', 'Ngăn 1 dây 6', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (8, 2, 'Điệu Disco cơ bản thường có nhịp phách như thế nào?', 'Nhịp 2/4 hoặc 4/4 rộn rã, dứt khoát', 'Nhịp 3/4 êm dịu điệu Valse', 'Nhịp 6/8 chậm rãi', 'Không có nhịp phách cố định', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (9, 2, 'Bí quyết để chuyển nhanh giữa các hợp âm mà không bị vấp tiếng là gì?', 'Giữ ngón tay sát phím đàn và tìm ngón chung làm trụ', 'Nhấc toàn bộ cả bàn tay ra thật xa cần đàn', 'Dừng gảy 5 giây để nhìn tay', 'Bấm thật mạnh cho đau ngón tay', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (10, 2, 'Khi ngón tay bị đau lúc mới tập guitar, cách khắc phục khoa học nhất là:', 'Tập đều đặn mỗi ngày 20-30 phút để hình thành vết chai tự nhiên', 'Bỏ đàn 2 tháng', 'Dùng băng keo quấn kín các đầu ngón tay', 'Bôi dầu hỏa vào ngón tay', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (11, 3, 'Trong bài thi IELTS Speaking Part 1, độ dài lý tưởng cho mỗi câu trả lời là:', 'Khoảng 2 đến 3 câu hoàn chỉnh có mở rộng ý tự nhiên', 'Chỉ trả lời đúng ''Yes'' hoặc ''No''', 'Nói độc thoại liên tục 10 phút', 'Im lặng mỉm cười chờ giám khảo hỏi tiếp', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (12, 3, 'Để nâng cao điểm tiêu chí Từ vựng (Lexical Resource), bạn nên sử dụng:', 'Collocations và từ đồng nghĩa ngữ cảnh tự nhiên', 'Từ cổ điển thế kỷ 18 khó hiểu', 'Từ viết tắt tiếng lóng tin nhắn', 'Lặp lại 1 từ duy nhất nhiều lần', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (13, 3, 'Khi gặp câu hỏi bất ngờ trong Speaking Part 1, chiến thuật câu giờ thông minh là:', 'Dùng filler phrase tự nhiên như ''That’s an interesting question...''', 'Nói to ''I don''t know'' rồi ngồi im', 'Xin phép giám khảo tra từ điển Google', 'Hỏi ngược lại giám khảo', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (14, 3, 'Tiêu chí ''Fluency and Coherence'' (Trôi chảy và mạch lạc) đánh giá điều gì?', 'Khả năng diễn đạt liên tục, có liên kết ý logic, ít ngập ngừng kéo dài', 'Nói thật nhanh như đọc ráp dù sai ngữ pháp', 'Giọng điệu phải giống 100% người bản xứ', 'Số lượng từ ngữ phát âm to nhất', 'A');
INSERT INTO quiz_questions (id, session_id, cau_hoi, lua_chon_a, lua_chon_b, lua_chon_c, lua_chon_d, dap_an_dung) VALUES (15, 3, 'Bí quyết tự tin luyện nói tiếng Anh hằng ngày cùng bạn bè là gì?', 'Tạo môi trường trao đổi thoải mái, không sợ mắc lỗi sai', 'Chỉ nói khi thuộc lòng 100% kịch bản', 'Chỉ luyện nói một mình trước gương trong bóng tối', 'Không bao giờ nói chuyện với ai', 'A');

-- Data for table: quiz_results (3 rows)
INSERT INTO quiz_results (id, session_id, user_id, tu_danh_gia_truoc, diem_so, thoi_gian_lam) VALUES (1, 1, 4, 2.0, 4.0, '2026-09-28 15:15:00');
INSERT INTO quiz_results (id, session_id, user_id, tu_danh_gia_truoc, diem_so, thoi_gian_lam) VALUES (2, 2, 5, 3.0, 5.0, '2026-09-29 16:45:00');
INSERT INTO quiz_results (id, session_id, user_id, tu_danh_gia_truoc, diem_so, thoi_gian_lam) VALUES (3, 3, 3, 2.0, 4.0, '2026-10-01 17:15:00');

-- Data for table: ratings (5 rows)
INSERT INTO ratings (id, session_id, nguoi_danh_gia_id, nguoi_duoc_danh_gia_id, so_sao, nhan_xet) VALUES (1, 1, 4, 3, 5, 'Anh An giảng Toán rất dễ hiểu, giải thích bài tập góc không gian siêu hay!');
INSERT INTO ratings (id, session_id, nguoi_danh_gia_id, nguoi_duoc_danh_gia_id, so_sao, nhan_xet) VALUES (2, 2, 5, 4, 5, 'Bình dạy đàn kiên nhẫn, chỉ cách chuyển hợp âm rất dễ nhớ.');
INSERT INTO ratings (id, session_id, nguoi_danh_gia_id, nguoi_duoc_danh_gia_id, so_sao, nhan_xet) VALUES (3, 3, 3, 5, 5, 'Chi phát âm chuẩn, sửa lỗi ngữ điệu cho mình rất nhiệt tình.');
INSERT INTO ratings (id, session_id, nguoi_danh_gia_id, nguoi_duoc_danh_gia_id, so_sao, nhan_xet) VALUES (4, 4, 6, 3, 5, 'Buổi học rất bổ ích, mình đã tự tin làm được bài kiểm tra.');
INSERT INTO ratings (id, session_id, nguoi_danh_gia_id, nguoi_duoc_danh_gia_id, so_sao, nhan_xet) VALUES (5, 5, 7, 6, 4, 'Minh chỉ code dễ hiểu, mong có thêm buổi học tiếp theo.');

-- Data for table: session_attendance (0 rows)

-- Data for table: sessions (5 rows)
INSERT INTO sessions (id, skill_id, nguoi_day_id, nguoi_hoc_id, thoi_gian_bat_dau, so_gio, trang_thai, ma_qr, checkin_day, checkin_hoc, dan_y_ai, quiz_dat_chuan) VALUES (1, 1, 3, 4, '2026-09-28 14:00:00', 1.0, 'hoan_thanh', 'QR_SES_001', 1, 1, 'Dàn ý AI: Khái niệm góc giữa hai mặt phẳng + 3 bài tập mẫu', 1);
INSERT INTO sessions (id, skill_id, nguoi_day_id, nguoi_hoc_id, thoi_gian_bat_dau, so_gio, trang_thai, ma_qr, checkin_day, checkin_hoc, dan_y_ai, quiz_dat_chuan) VALUES (2, 2, 4, 5, '2026-09-29 15:30:00', 1.0, 'hoan_thanh', 'QR_SES_002', 1, 1, 'Dàn ý AI: Hợp âm C-Am-Dm-G7 + bài tập bấm tay', 1);
INSERT INTO sessions (id, skill_id, nguoi_day_id, nguoi_hoc_id, thoi_gian_bat_dau, so_gio, trang_thai, ma_qr, checkin_day, checkin_hoc, dan_y_ai, quiz_dat_chuan) VALUES (3, 3, 5, 3, '2026-10-01 16:00:00', 1.0, 'hoan_thanh', 'QR_SES_003', 1, 1, 'Dàn ý AI: Chủ đề Hometown & Hobbies', 1);
INSERT INTO sessions (id, skill_id, nguoi_day_id, nguoi_hoc_id, thoi_gian_bat_dau, so_gio, trang_thai, ma_qr, checkin_day, checkin_hoc, dan_y_ai, quiz_dat_chuan) VALUES (4, 1, 3, 6, '2026-10-03 09:00:00', 1.0, 'hoan_thanh', 'QR_SES_004', 1, 1, 'Dàn ý AI: Góc giữa đường thẳng và mặt phẳng', 1);
INSERT INTO sessions (id, skill_id, nguoi_day_id, nguoi_hoc_id, thoi_gian_bat_dau, so_gio, trang_thai, ma_qr, checkin_day, checkin_hoc, dan_y_ai, quiz_dat_chuan) VALUES (5, 4, 6, 7, '2026-10-04 14:30:00', 1.0, 'hoan_thanh', 'QR_SES_005', 1, 1, 'Dàn ý AI: Biến số và lệnh input/print trong Python', 1);

-- Data for table: skills (7 rows)
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (1, 3, 'Toán học', 'Ôn tập Hình học không gian lớp 12', 'Phương pháp giải nhanh trắc nghiệm khoảng cách và góc', 'da_duyet', 'Nội dung bổ ích, phù hợp chương trình');
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (2, 4, 'Năng khiếu', 'Đệm hát Guitar cơ bản cho người mới', 'Cách bấm các hợp âm chuẩn và kỹ thuật quạt chả điệu Disco', 'da_duyet', 'Kỹ năng giải trí tích cực');
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (3, 5, 'Ngoại ngữ', 'Luyện phản xạ nói Tiếng Anh IELTS Speaking', 'Chiến thuật trả lời Part 1 và Part 2 tự nhiên, lưu loát', 'da_duyet', 'Rất hữu ích cho học sinh hội nhập');
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (4, 6, 'Tin học', 'Lập trình Python cho người mới bắt đầu', 'Cấu trúc rẽ nhánh, vòng lặp và xử lý chuỗi căn bản', 'da_duyet', 'Định hướng chuyển đổi số trường học');
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (5, 7, 'Khoa học', 'Phương pháp làm bài thí nghiệm Hóa học 12', 'Giải thích hiện tượng và mẹo nhớ tính chất kim loại kiềm', 'cho_duyet', 'Chờ giáo viên bộ môn duyệt nội dung');
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (6, 5, 'Toán học', 'Phương pháp vẽ đồ thị và khảo sát hàm số 12', 'Kỹ thuật nhận diện bảng biến thiên và cực trị hàm số', 'da_duyet', 'Nội dung trọng tâm thi tốt nghiệp THPT');
INSERT INTO skills (id, user_id, linh_vuc, tieu_de, mo_ta, trang_thai_duyet, ly_do_ai_kiem_duyet) VALUES (7, 7, 'Toán học', 'Bí quyết giải nhanh Toán Xác suất và Thống kê', 'Phương pháp tư duy sơ đồ cây và bài toán xác suất thực tế', 'da_duyet', 'Rèn luyện tư duy logic và suy luận');

-- Data for table: task_registrations (2 rows)
INSERT INTO task_registrations (id, task_id, user_id, trang_thai, thoi_gian_dang_ky) VALUES (1, 4, 3, 'hoan_thanh', '2026-10-04 08:15:00');
INSERT INTO task_registrations (id, task_id, user_id, trang_thai, thoi_gian_dang_ky) VALUES (2, 2, 4, 'da_dang_ky', '2026-10-05 08:45:00');

-- Data for table: users (7 rows)
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (1, 'admin', 'Quản trị viên Hệ thống', 'Ban Giám Hiệu', 'admin', 100.0, 'Toàn thời gian', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (2, 'GV001', 'Thầy Nguyễn Văn Đức', 'Tổ Toán - Tin', 'giao_vien', 10.0, 'Các buổi chiều trong tuần', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (3, 'HS12001', 'Nguyễn Hoàng An', '12A1', 'hoc_sinh', 3.5, 'Chiều thứ 3, sáng thứ 7', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (4, 'HS11002', 'Trần Thanh Bình', '11B2', 'hoc_sinh', 2.5, 'Sáng Chủ nhật, tối thứ 5', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (5, 'HS10003', 'Lê Kim Chi', '10A3', 'hoc_sinh', 3.0, 'Chiều thứ 6, sáng Chủ nhật', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (6, 'HS11004', 'Phạm Quang Minh', '11A1', 'hoc_sinh', 2.0, 'Tối thứ 2, tối thứ 4', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');
INSERT INTO users (id, ma_hoc_sinh, ho_ten, lop, vai_tro, so_du_gio, gio_ranh, mat_khau) VALUES (7, 'HS12005', 'Vũ Thu Hà', '12D2', 'hoc_sinh', 2.0, 'Sáng thứ 7, chiều Chủ nhật', 'scrypt:32768:8:1$ZAHojaujV35QhWe5$7b94fa9125d98487864e34924cc9a78f97db02e2c1abd4000193c28bf3995c3720ef28c918d6ac36d6c4e8ebae4ff932d022089c84520833d2543e49b7a92b85');

