with open('templates/skills_market.html', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = [
    ("{% block title %}Kho kỹ năng học đường - {{ config.ten_truong }}{% endblock %}",
     "{% block title %}{{ _('Kho kỹ năng học đường') }} - {{ config.ten_truong }}{% endblock %}"),
    ('<i class="bi bi-shop me-1"></i> KHÔNG GIAN TRAO ĐỔI TRI THỨC',
     '<i class="bi bi-shop me-1"></i> {{ _(\'KHÔNG GIAN TRAO ĐỔI TRI THỨC\') }}'),
    ('<h2 class="fw-bold mb-0 text-dark">Kho Kỹ Năng Học Đường</h2>',
     '<h2 class="fw-bold mb-0 text-dark">{{ _(\'Kho Kỹ Năng Học Đường\') }}</h2>'),
    ('<p class="text-muted small mb-0">Chỉ hiển thị các chuyên đề đã qua kiểm duyệt sư phạm bởi giáo viên {{ config.ten_truong }}</p>',
     '<p class="text-muted small mb-0">{{ _(\'Chỉ hiển thị các chuyên đề đã qua kiểm duyệt sư phạm bởi giáo viên\') }} {{ config.ten_truong }}</p>'),
    ('<i class="bi bi-stars text-danger me-1"></i> AI Gợi Ý Ghép Cặp',
     '<i class="bi bi-stars text-danger me-1"></i> {{ _(\'AI Gợi Ý Ghép Cặp\') }}'),
    ('<i class="bi bi-plus-circle me-1"></i> Đăng kỹ năng của bạn',
     '<i class="bi bi-plus-circle me-1"></i> {{ _(\'Đăng kỹ năng của bạn\') }}'),
    ('<i class="bi bi-box-arrow-in-right me-1"></i> Đăng nhập để chia sẻ & học',
     '<i class="bi bi-box-arrow-in-right me-1"></i> {{ _(\'Đăng nhập để chia sẻ & học\') }}'),
    ('placeholder="Tìm kỹ năng theo từ khóa (Toán, Guitar, Python, IELTS...)"',
     'placeholder="{{ _(\'Tìm kỹ năng theo từ khóa (Toán, Guitar, Python, IELTS...)\') }}"'),
    ('<option value="">-- Tất cả lĩnh vực --</option>',
     '<option value="">-- {{ _(\'Tất cả lĩnh vực\') }} --</option>'),
    ('<i class="bi bi-funnel me-1"></i> Lọc',
     '<i class="bi bi-funnel me-1"></i> {{ _(\'Lọc\') }}'),
    ('title="Xóa bộ lọc"', 'title="{{ _(\'Xóa bộ lọc\') }}"'),
    ('<i class="bi bi-patch-check-fill me-1"></i>Đã duyệt',
     '<i class="bi bi-patch-check-fill me-1"></i>{{ _(\'Đã duyệt\') }}'),
    ('<div class="text-muted" style="font-size: 0.75rem;">Lớp: {{ skill.lop }} • Mã: <code>{{ skill.ma_hoc_sinh }}</code></div>',
     '<div class="text-muted" style="font-size: 0.75rem;">{{ _(\'Lớp:\') }} {{ skill.lop }} • {{ _(\'Mã:\') }} <code>{{ skill.ma_hoc_sinh }}</code></div>'),
    ('<span class="text-muted">Đánh giá:</span>',
     '<span class="text-muted">{{ _(\'Đánh giá:\') }}</span>'),
    ('title="Đây là kỹ năng bạn chia sẻ"',
     'title="{{ _(\'Đây là kỹ năng bạn chia sẻ\') }}"'),
    ('<i class="bi bi-person-check me-1"></i> Kỹ năng của bạn',
     '<i class="bi bi-person-check me-1"></i> {{ _(\'Kỹ năng của bạn\') }}'),
    ('<i class="bi bi-calendar-plus me-1"></i> Đặt lịch học ngay (Tối đa 2h)',
     '<i class="bi bi-calendar-plus me-1"></i> {{ _(\'Đặt lịch học ngay (Tối đa 2h)\') }}'),
    ('<i class="bi bi-box-arrow-in-right me-1"></i> Đăng nhập để đặt lịch',
     '<i class="bi bi-box-arrow-in-right me-1"></i> {{ _(\'Đăng nhập để đặt lịch\') }}'),
    ('>Đặt lịch học kỹ năng</h5>',
     '>{{ _(\'Đặt lịch học kỹ năng\') }}</h5>'),
    ('<div class="text-muted"><i class="bi bi-person-badge me-1"></i>Gia sư bạn học: <strong>{{ skill.ho_ten }}</strong> (Lớp {{ skill.lop }})</div>',
     '<div class="text-muted"><i class="bi bi-person-badge me-1"></i>{{ _(\'Gia sư bạn học:\') }} <strong>{{ skill.ho_ten }}</strong> ({{ _(\'Lớp\') }} {{ skill.lop }})</div>'),
    ('<div class="text-muted"><i class="bi bi-wallet2 me-1"></i>Số dư hiện có của bạn: <strong>{{ "%.1f"|format(current_user.so_du_gio) }} giờ</strong></div>',
     '<div class="text-muted"><i class="bi bi-wallet2 me-1"></i>{{ _(\'Số dư hiện có của bạn:\') }} <strong>{{ "%.1f"|format(current_user.so_du_gio) }} {{ _(\'giờ\') }}</strong></div>'),
    ('<label for="thoi_gian_bat_dau_{{ skill.id }}" class="form-label small fw-semibold">Thời gian hẹn học <span class="text-danger">*</span></label>',
     '<label for="thoi_gian_bat_dau_{{ skill.id }}" class="form-label small fw-semibold">{{ _(\'Thời gian hẹn học\') }} <span class="text-danger">*</span></label>'),
    ('<div class="form-text small text-muted">Chọn ngày và giờ phù hợp với thời gian rảnh của cả hai bạn.</div>',
     '<div class="form-text small text-muted">{{ _(\'Chọn ngày và giờ phù hợp với thời gian rảnh của cả hai bạn.\') }}</div>'),
    ('<label for="so_gio_{{ skill.id }}" class="form-label small fw-semibold">Thời lượng buổi học (giờ) <span class="text-danger">*</span></label>',
     '<label for="so_gio_{{ skill.id }}" class="form-label small fw-semibold">{{ _(\'Thời lượng buổi học (giờ)\') }} <span class="text-danger">*</span></label>'),
    ('<option value="1.0" selected>1.0 giờ (1 tín dụng)</option>',
     '<option value="1.0" selected>{{ _(\'1.0 giờ (1 tín dụng)\') }}</option>'),
    ('<option value="0.5">0.5 giờ (30 phút - 0.5 tín dụng)</option>',
     '<option value="0.5">{{ _(\'0.5 giờ (30 phút - 0.5 tín dụng)\') }}</option>'),
    ('<option value="1.5">1.5 giờ (90 phút - 1.5 tín dụng)</option>',
     '<option value="1.5">{{ _(\'1.5 giờ (90 phút - 1.5 tín dụng)\') }}</option>'),
    ('<option value="2.0">2.0 giờ (Tối đa 2h / phiên - 2.0 tín dụng)</option>',
     '<option value="2.0">{{ _(\'2.0 giờ (Tối đa 2h / phiên - 2.0 tín dụng)\') }}</option>'),
    ('<div class="form-text small text-primary"><i class="bi bi-info-circle me-1"></i>Quy định hệ thống: Tối đa 2.0 giờ/phiên học.</div>',
     '<div class="form-text small text-primary"><i class="bi bi-info-circle me-1"></i>{{ _(\'Quy định hệ thống: Tối đa 2.0 giờ/phiên học.\') }}</div>'),
    ('<i class="bi bi-shield-lock me-1"></i> Khi hoàn thành buổi học, tín dụng thời gian sẽ tự động chuyển từ bạn sang bạn gia sư theo xác nhận 2 chiều.',
     '<i class="bi bi-shield-lock me-1"></i> {{ _(\'Khi hoàn thành buổi học, tín dụng thời gian sẽ tự động chuyển từ bạn sang bạn gia sư theo xác nhận 2 chiều.\') }}'),
    ('<button type="button" class="btn btn-outline-secondary w-50" data-bs-dismiss="modal">Hủy</button>',
     '<button type="button" class="btn btn-outline-secondary w-50" data-bs-dismiss="modal">{{ _(\'Hủy\') }}</button>'),
    ('<i class="bi bi-calendar-check me-1"></i> Xác nhận đặt lịch',
     '<i class="bi bi-calendar-check me-1"></i> {{ _(\'Xác nhận đặt lịch\') }}'),
    ('<h5 class="fw-bold text-dark mb-1">Chưa có kỹ năng phù hợp</h5>',
     '<h5 class="fw-bold text-dark mb-1">{{ _(\'Chưa có kỹ năng phù hợp\') }}</h5>'),
    ('<p class="text-muted small mb-3">Hiện tại chưa có kỹ năng nào thuộc lĩnh vực hoặc từ khóa tìm kiếm của bạn.</p>',
     '<p class="text-muted small mb-3">{{ _(\'Hiện tại chưa có kỹ năng nào thuộc lĩnh vực hoặc từ khóa tìm kiếm của bạn.\') }}</p>'),
    ('<i class="bi bi-arrow-clockwise me-1"></i> Xem tất cả kỹ năng',
     '<i class="bi bi-arrow-clockwise me-1"></i> {{ _(\'Xem tất cả kỹ năng\') }}'),
]

for s, d in replacements:
    content = content.replace(s, d)

with open('templates/skills_market.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("skills_market.html updated.")
