import re
import os

with open('templates/admin.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Let's define the comprehensive mapping of unwrapped text to wrapped text for admin.html
# We must ensure that we never double wrap (check if already wrapped).

# 1. Attributes replacements
replacements = [
    # Page Title
    ("{% block title %}Bảng điều khiển Quản trị - School Time Bank{% endblock %}",
     "{% block title %}{{ _('Bảng điều khiển Quản trị - School Time Bank') }}{% endblock %}"),

    # Badges & Headers
    ('<span class="badge bg-danger px-3 py-2 rounded-pill"><i class="bi bi-shield-lock-fill me-1"></i> TỔNG QUẢN TRỊ (SUPER ADMIN)</span>',
     '<span class="badge bg-danger px-3 py-2 rounded-pill"><i class="bi bi-shield-lock-fill me-1"></i> {{ _(\'TỔNG QUẢN TRỊ (SUPER ADMIN)\') }}</span>'),
    ('<span class="badge bg-primary px-3 py-2 rounded-pill"><i class="bi bi-building-fill me-1"></i> QUẢN TRỊ VIÊN TRƯỜNG (SCHOOL ADMIN)</span>',
     '<span class="badge bg-primary px-3 py-2 rounded-pill"><i class="bi bi-building-fill me-1"></i> {{ _(\'QUẢN TRỊ VIÊN TRƯỜNG (SCHOOL ADMIN)\') }}</span>'),
    ('<h2 class="fw-bold mb-0 text-dark">Hệ thống Quản trị Đa trường học</h2>',
     '<h2 class="fw-bold mb-0 text-dark">{{ _(\'Hệ thống Quản trị Đa trường học\') }}</h2>'),
    ('<p class="text-muted small mb-0">School Time Bank — Phân quyền & Giám sát Giáo dục Toàn diện</p>',
     '<p class="text-muted small mb-0">{{ _(\'School Time Bank — Phân quyền & Giám sát Giáo dục Toàn diện\') }}</p>'),
    ('<label for="filterTruong" class="small text-muted fw-semibold text-nowrap"><i class="bi bi-funnel-fill me-1"></i>Trường:</label>',
     '<label for="filterTruong" class="small text-muted fw-semibold text-nowrap"><i class="bi bi-funnel-fill me-1"></i>{{ _(\'Trường:\') }}</label>'),
    ('<option value="" {% if not selected_truong_id %}selected{% endif %}>-- Tất cả các trường ({{ all_schools|length }} trường) --</option>',
     '<option value="" {% if not selected_truong_id %}selected{% endif %}>-- {{ _(\'Tất cả các trường\') }} ({{ all_schools|length }} {{ _(\'trường\') }}) --</option>'),
    ('{% if s.an_truong == 1 %} (Đã ẩn){% endif %}',
     '{% if s.an_truong == 1 %} ({{ _(\'Đã ẩn\') }}){% endif %}'),
    
    # Top Action Buttons
    ('<i class="bi bi-people-fill me-1"></i> Quản lý Tài khoản',
     '<i class="bi bi-people-fill me-1"></i> {{ _(\'Quản lý Tài khoản\') }}'),
    ('onsubmit="return confirm(\'Khôi phục dữ liệu Trường Demo về trạng thái ban đầu?\');"',
     'onsubmit="return confirm(\'{{ _(\'Khôi phục dữ liệu Trường Demo về trạng thái ban đầu?\') }}\');"'),
    ('<i class="bi bi-file-earmark-spreadsheet me-1"></i> Xuất CSV',
     '<i class="bi bi-file-earmark-spreadsheet me-1"></i> {{ _(\'Xuất CSV\') }}'),
    ('<i class="bi bi-camera-video me-1"></i> Giám sát Phòng học ảo',
     '<i class="bi bi-camera-video me-1"></i> {{ _(\'Giám sát Phòng học ảo\') }}'),
    ('<i class="bi bi-patch-check me-1"></i> Duyệt Kỹ Năng',
     '<i class="bi bi-patch-check me-1"></i> {{ _(\'Duyệt Kỹ Năng\') }}'),
    ('<i class="bi bi-image me-1"></i> Tải Logo Trường',
     '<i class="bi bi-image me-1"></i> {{ _(\'Tải Logo Trường\') }}'),

    # Tab Nav Items
    ('<i class="bi bi-speedometer2 me-1"></i> Tổng quan & Báo cáo',
     '<i class="bi bi-speedometer2 me-1"></i> {{ _(\'Tổng quan & Báo cáo\') }}'),
    ('<i class="bi bi-hourglass-split me-1"></i> Hàng chờ duyệt học sinh',
     '<i class="bi bi-hourglass-split me-1"></i> {{ _(\'Hàng chờ duyệt học sinh\') }}'),
    ('<i class="bi bi-ticket-perforated me-1"></i> Quản lý Mã mời',
     '<i class="bi bi-ticket-perforated me-1"></i> {{ _(\'Quản lý Mã mời\') }}'),
    ('<i class="bi bi-file-earmark-arrow-up-fill me-1"></i> Nhập danh sách',
     '<i class="bi bi-file-earmark-arrow-up-fill me-1"></i> {{ _(\'Nhập danh sách\') }}'),
    ('<i class="bi bi-shield-exclamation me-1"></i> Xử lý Vi phạm & Báo cáo',
     '<i class="bi bi-shield-exclamation me-1"></i> {{ _(\'Xử lý Vi phạm & Báo cáo\') }}'),
    ('<i class="bi bi-people me-1"></i> Danh sách Tài khoản',
     '<i class="bi bi-people me-1"></i> {{ _(\'Danh sách Tài khoản\') }}'),
    ('<i class="bi bi-globe2 text-warning me-1"></i> Duyệt Liên Trường',
     '<i class="bi bi-globe2 text-warning me-1"></i> {{ _(\'Duyệt Liên Trường\') }}'),
    ('<i class="bi bi-heart-fill me-1"></i> Chương trình Cộng đồng',
     '<i class="bi bi-heart-fill me-1"></i> {{ _(\'Chương trình Cộng đồng\') }}'),
    ('<i class="bi bi-buildings-fill me-1"></i> Quản lý Trường học',
     '<i class="bi bi-buildings-fill me-1"></i> {{ _(\'Quản lý Trường học\') }}'),

    # Stat Cards
    ('<span class="text-muted small">Tổng phiên học</span>',
     '<span class="text-muted small">{{ _(\'Tổng phiên học\') }}</span>'),
    ('<small class="text-muted">Đang quản trị</small>',
     '<small class="text-muted">{{ _(\'Đang quản trị\') }}</small>'),
    ('<span class="text-muted small">Tổng giờ lưu thông</span>',
     '<span class="text-muted small">{{ _(\'Tổng giờ lưu thông\') }}</span>'),
    ('<small class="text-muted">Hoàn thành</small>',
     '<small class="text-muted">{{ _(\'Hoàn thành\') }}</small>'),
    ('<span class="text-muted small">Học sinh thành viên</span>',
     '<span class="text-muted small">{{ _(\'Học sinh thành viên\') }}</span>'),
    ('<small class="text-muted">Đã mở sổ tín dụng</small>',
     '<small class="text-muted">{{ _(\'Đã mở sổ tín dụng\') }}</small>'),
    ('<span class="text-muted small">Tổng tài khoản</span>',
     '<span class="text-muted small">{{ _(\'Tổng tài khoản\') }}</span>'),
    ('<small class="text-muted">HS + GV + Quản trị</small>',
     '<small class="text-muted">{{ _(\'HS + GV + Quản trị\') }}</small>'),
    ('<span class="text-muted small">Giờ trong ví</span>',
     '<span class="text-muted small">{{ _(\'Giờ trong ví\') }}</span>'),
    ('<small class="text-muted">Vốn khả dụng</small>',
     '<small class="text-muted">{{ _(\'Vốn khả dụng\') }}</small>'),
    ('<span class="text-muted small">Kỹ năng chờ duyệt</span>',
     '<span class="text-muted small">{{ _(\'Kỹ năng chờ duyệt\') }}</span>'),
    ('<small class="text-muted">Cần GV duyệt tay</small>',
     '<small class="text-muted">{{ _(\'Cần GV duyệt tay\') }}</small>'),

    # Early Warnings
    ('<span class="badge bg-danger rounded-pill px-2 py-1"><i class="bi bi-shield-exclamation me-1"></i> CẢNH BÁO SỚM SƯ PHẠM</span>',
     '<span class="badge bg-danger rounded-pill px-2 py-1"><i class="bi bi-shield-exclamation me-1"></i> {{ _(\'CẢNH BÁO SỚM SƯ PHẠM\') }}</span>'),
    ('<span class="badge-ai" style="font-size: 0.75rem;"><i class="bi bi-stars"></i> Hỗ trợ bởi AI (Trí tuệ nhân tạo)</span>',
     '<span class="badge-ai" style="font-size: 0.75rem;"><i class="bi bi-stars"></i> {{ _(\'Hỗ trợ bởi AI (Trí tuệ nhân tạo)\') }}</span>'),
    ('<h5 class="fw-bold mb-0 text-dark mt-1">Phát Hiện Nguy Cơ Học Đường Cần Can Thiệp</h5>',
     '<h5 class="fw-bold mb-0 text-dark mt-1">{{ _(\'Phát Hiện Nguy Cơ Học Đường Cần Can Thiệp\') }}</h5>'),
    ('<small class="text-muted">Quét học sinh ngưng hoạt động (>7 ngày) và cặp đôi xung đột (≤2★)</small>',
     '<small class="text-muted">{{ _(\'Quét học sinh ngưng hoạt động (>7 ngày) và cặp đôi xung đột (≤2★)\') }}</small>'),
    ('<i class="bi bi-person-x-fill text-danger me-1"></i>Học sinh > 7 ngày không tham gia phiên',
     '<i class="bi bi-person-x-fill text-danger me-1"></i>{{ _(\'Học sinh > 7 ngày không tham gia phiên\') }}'),
    ('<span class="badge bg-light text-secondary border">Lớp {{ s.lop }}</span>',
     '<span class="badge bg-light text-secondary border">{{ _(\'Lớp\') }} {{ s.lop }}</span>'),
    ('<i class="bi bi-check-circle-fill text-success me-1"></i> Mọi học sinh đều duy trì hoạt động đều đặn.',
     '<i class="bi bi-check-circle-fill text-success me-1"></i> {{ _(\'Mọi học sinh đều duy trì hoạt động đều đặn.\') }}'),
    ('<i class="bi bi-exclamation-triangle-fill text-warning me-1"></i>Cặp đôi đánh giá ≤ 2★ từ 2 lần trở lên',
     '<i class="bi bi-exclamation-triangle-fill text-warning me-1"></i>{{ _(\'Cặp đôi đánh giá ≤ 2★ từ 2 lần trở lên\') }}'),
    ('<i class="bi bi-check-circle-fill text-success me-1"></i> Không ghi nhận cặp đôi nào có xung đột đánh giá thấp lặp lại.',
     '<i class="bi bi-check-circle-fill text-success me-1"></i> {{ _(\'Không ghi nhận cặp đôi nào có xung đột đánh giá thấp lặp lại.\') }}'),
    ('<i class="bi bi-magic me-1"></i> Đề xuất can thiệp sư phạm nhân văn từ AI:',
     '<i class="bi bi-magic me-1"></i> {{ _(\'Đề xuất can thiệp sư phạm nhân văn từ AI:\') }}'),

    # Learning Results
    ('<i class="bi bi-mortarboard-fill me-1"></i> KẾT QUẢ HỌC TẬP',
     '<i class="bi bi-mortarboard-fill me-1"></i> {{ _(\'KẾT QUẢ HỌC TẬP\') }}'),
    ('<h5 class="fw-bold mb-0 text-dark mt-1">Đo Lường Chất Lượng & Tiến Bộ Năng Lực Học Sinh</h5>',
     '<h5 class="fw-bold mb-0 text-dark mt-1">{{ _(\'Đo Lường Chất Lượng & Tiến Bộ Năng Lực Học Sinh\') }}</h5>'),
    ('Quiz xác nhận kết quả cho giáo viên, <strong>không chặn</strong> chuyển giờ.',
     '{{ _(\'Quiz xác nhận kết quả cho giáo viên, không chặn chuyển giờ.\') }}'),
    ('<span class="text-muted small d-block mb-1">Phiên đạt chuẩn Quiz (≥60%)</span>',
     '<span class="text-muted small d-block mb-1">{{ _(\'Phiên đạt chuẩn Quiz (≥60%)\') }}</span>'),
    ('phiên</div>\n                </div>',
     '{{ _(\'phiên\') }}</div>\n                </div>'),
    ('<span class="text-muted small d-block mb-1">Tỷ lệ xuất sắc (≥4/5)</span>',
     '<span class="text-muted small d-block mb-1">{{ _(\'Tỷ lệ xuất sắc (≥4/5)\') }}</span>'),
    ('bài làm</div>\n                </div>',
     '{{ _(\'bài làm\') }}</div>\n                </div>'),
    ('<span class="text-muted small d-block mb-1">So sánh Trước vs Sau</span>',
     '<span class="text-muted small d-block mb-1">{{ _(\'So sánh Trước vs Sau\') }}</span>'),
    ('Tiến bộ: +',
     '{{ _(\'Tiến bộ:\') }} +'),
    (' điểm</div>\n                </div>',
     ' {{ _(\'điểm\') }}</div>\n                </div>'),
    ('<span class="text-muted small d-block mb-1">Tổng lượt hoàn thành</span>',
     '<span class="text-muted small d-block mb-1">{{ _(\'Tổng lượt hoàn thành\') }}</span>'),
    ('<div class="small text-muted mt-1">Lượt làm trắc nghiệm</div>',
     '<div class="small text-muted mt-1">{{ _(\'Lượt làm trắc nghiệm\') }}</div>'),

    # Honor Roll
    ('<i class="bi bi-trophy-fill me-1"></i> BẢNG VINH DANH SƯ PHẠM',
     '<i class="bi bi-trophy-fill me-1"></i> {{ _(\'BẢNG VINH DANH SƯ PHẠM\') }}'),
    ('<h5 class="fw-bold mb-0 text-dark mt-1">Top Học Sinh Tích Cực Trao Đổi Tri Thức Nhất</h5>',
     '<h5 class="fw-bold mb-0 text-dark mt-1">{{ _(\'Top Học Sinh Tích Cực Trao Đổi Tri Thức Nhất\') }}</h5>'),
    ('<small class="text-muted"><i class="bi bi-award me-1 text-warning"></i>Vinh danh gương sáng học tập & chia sẻ kỹ năng</small>',
     '<small class="text-muted"><i class="bi bi-award me-1 text-warning"></i>{{ _(\'Vinh danh gương sáng học tập & chia sẻ kỹ năng\') }}</small>'),
    ('<th class="ps-3" style="width: 80px;">Xếp hạng</th>',
     '<th class="ps-3" style="width: 80px;">{{ _(\'Xếp hạng\') }}</th>'),
    ('<th>Mã HS</th>', '<th>{{ _(\'Mã HS\') }}</th>'),
    ('<th>Họ và tên</th>', '<th>{{ _(\'Họ và tên\') }}</th>'),
    ('<th>Lớp</th>', '<th>{{ _(\'Lớp\') }}</th>'),
    ('<th class="text-center">Giờ đã dạy</th>', '<th class="text-center">{{ _(\'Giờ đã dạy\') }}</th>'),
    ('<th class="text-center">Giờ đã học</th>', '<th class="text-center">{{ _(\'Giờ đã học\') }}</th>'),
    ('<th class="text-center">Phiên hoàn thành</th>', '<th class="text-center">{{ _(\'Phiên hoàn thành\') }}</th>'),
    ('<th class="text-end pe-3">Số dư hiện tại</th>', '<th class="text-end pe-3">{{ _(\'Số dư hiện tại\') }}</th>'),
    ('<td class="text-center">{{ st.so_phien }} phiên</td>',
     '<td class="text-center">{{ st.so_phien }} {{ _(\'phiên\') }}</td>'),

    # Pending Students
    ('<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-person-check-fill text-warning me-2"></i>Hàng Chờ Duyệt Mở Sổ Học Sinh</h5>',
     '<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-person-check-fill text-warning me-2"></i>{{ _(\'Hàng Chờ Duyệt Mở Sổ Học Sinh\') }}</h5>'),
    ('Tổng quản trị thấy toàn bộ hàng chờ các trường. Quản trị trường chỉ duyệt học sinh trường mình.',
     '{{ _(\'Tổng quản trị thấy toàn bộ hàng chờ các trường. Quản trị trường chỉ duyệt học sinh trường mình.\') }}'),
    ('chưa có mã mời đang chờ duyệt.',
     '{{ _(\'chưa có mã mời đang chờ duyệt.\') }}'),
    ('onsubmit="return confirm(\'Bạn có chắc chắn muốn DUYỆT TẤT CẢ học sinh đang chờ trong danh sách này?\');"',
     'onsubmit="return confirm(\'{{ _(\'Bạn có chắc chắn muốn DUYỆT TẤT CẢ học sinh đang chờ trong danh sách này?\') }}\');"'),
    ('<i class="bi bi-check-all me-1"></i> Duyệt tất cả',
     '<i class="bi bi-check-all me-1"></i> {{ _(\'Duyệt tất cả\') }}'),
    ('<th>Trường học</th>', '<th>{{ _(\'Trường học\') }}</th>'),
    ('<th>Khung giờ rảnh</th>', '<th>{{ _(\'Khung giờ rảnh\') }}</th>'),
    ('<th>Trạng thái</th>', '<th>{{ _(\'Trạng thái\') }}</th>'),
    ('<th class="text-end pe-3">Thao tác</th>', '<th class="text-end pe-3">{{ _(\'Thao tác\') }}</th>'),
    ('<span class="badge bg-warning text-dark"><i class="bi bi-clock me-1"></i>Chờ duyệt</span>',
     '<span class="badge bg-warning text-dark"><i class="bi bi-clock me-1"></i>{{ _(\'Chờ duyệt\') }}</span>'),
    ('<i class="bi bi-check-lg me-1"></i>Duyệt',
     '<i class="bi bi-check-lg me-1"></i>{{ _(\'Duyệt\') }}'),
    ('onclick="return confirm(\'Bạn có chắc muốn từ chối đăng ký này?\');"',
     'onclick="return confirm(\'{{ _(\'Bạn có chắc muốn từ chối đăng ký này?\') }}\');"'),
    ('<i class="bi bi-x-lg me-1"></i>Từ chối',
     '<i class="bi bi-x-lg me-1"></i>{{ _(\'Từ chối\') }}'),
    ('<h6 class="fw-bold">Hàng chờ trống!</h6>',
     '<h6 class="fw-bold">{{ _(\'Hàng chờ trống!\') }}</h6>'),
    ('<p class="small mb-0">Tất cả tài khoản học sinh đã được duyệt hoặc đăng ký hợp lệ qua mã mời.</p>',
     '<p class="small mb-0">{{ _(\'Tất cả tài khoản học sinh đã được duyệt hoặc đăng ký hợp lệ qua mã mời.\') }}</p>'),

    # Generate Invite Code
    ('<h5 class="fw-bold text-dark mb-2"><i class="bi bi-plus-circle-fill text-primary me-2"></i>Sinh Mã Mời Trường Học Ngẫu Nhiên</h5>',
     '<h5 class="fw-bold text-dark mb-2"><i class="bi bi-plus-circle-fill text-primary me-2"></i>{{ _(\'Sinh Mã Mời Trường Học Ngẫu Nhiên\') }}</h5>'),
    ('<p class="text-muted small mb-4">Hệ thống tạo mã định dạng chuẩn <code>TBEDU-XXXX-XXXX</code> chống mạo danh học sinh trường khác.</p>',
     '<p class="text-muted small mb-4">{{ _(\'Hệ thống tạo mã định dạng chuẩn TBEDU-XXXX-XXXX chống mạo danh học sinh trường khác.\') }}</p>'),
    ('<label class="form-label small fw-semibold">Áp dụng cho trường <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Áp dụng cho trường\') }} <span class="text-danger">*</span></label>'),
    ('<label class="form-label small fw-semibold">Loại mã mời <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Loại mã mời\') }} <span class="text-danger">*</span></label>'),
    ('<option value="ca_nhan">Mã cá nhân (Nhiều mã, mỗi mã 1 lượt)</option>',
     '<option value="ca_nhan">{{ _(\'Mã cá nhân (Nhiều mã, mỗi mã 1 lượt)\') }}</option>'),
    ('<option value="lop">Mã lớp (1 mã, dùng chung cho cả lớp)</option>',
     '<option value="lop">{{ _(\'Mã lớp (1 mã, dùng chung cho cả lớp)\') }}</option>'),
    ('<label class="form-label small fw-semibold" id="lblSoLuong">Số lượng mã cần tạo</label>',
     '<label class="form-label small fw-semibold" id="lblSoLuong">{{ _(\'Số lượng mã cần tạo\') }}</label>'),
    ('<label class="form-label small fw-semibold">Số lượt dùng tối đa / mã</label>',
     '<label class="form-label small fw-semibold">{{ _(\'Số lượt dùng tối đa / mã\') }}</label>'),
    ('<i class="bi bi-magic me-1"></i> Sinh mã ngay',
     '<i class="bi bi-magic me-1"></i> {{ _(\'Sinh mã ngay\') }}'),

    # Invite Code Table
    ('<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-table me-2 text-primary"></i>Danh Sách Mã Mời Đã Phát Hành</h5>',
     '<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-table me-2 text-primary"></i>{{ _(\'Danh Sách Mã Mời Đã Phát Hành\') }}</h5>'),
    ('<span class="badge bg-light text-dark border">Cập nhật tự động</span>',
     '<span class="badge bg-light text-dark border">{{ _(\'Cập nhật tự động\') }}</span>'),
    ('<th class="ps-3">Mã mời</th>', '<th class="ps-3">{{ _(\'Mã mời\') }}</th>'),
    ('<th>Trường áp dụng</th>', '<th>{{ _(\'Trường áp dụng\') }}</th>'),
    ('<th>Loại mã</th>', '<th>{{ _(\'Loại mã\') }}</th>'),
    ('<th class="text-center">Tối đa</th>', '<th class="text-center">{{ _(\'Tối đa\') }}</th>'),
    ('<th class="text-center">Đã dùng</th>', '<th class="text-center">{{ _(\'Đã dùng\') }}</th>'),
    ('<th class="text-center">Còn lại</th>', '<th class="text-center">{{ _(\'Còn lại\') }}</th>'),
    ('<th>Học sinh đã dùng</th>', '<th>{{ _(\'Học sinh đã dùng\') }}</th>'),
    ('<th>Ngày tạo</th>', '<th>{{ _(\'Ngày tạo\') }}</th>'),
    ('<span class="badge bg-info-subtle text-info fw-bold">Mã lớp</span>',
     '<span class="badge bg-info-subtle text-info fw-bold">{{ _(\'Mã lớp\') }}</span>'),
    ('<span class="badge bg-secondary-subtle text-secondary">Cá nhân</span>',
     '<span class="badge bg-secondary-subtle text-secondary">{{ _(\'Cá nhân\') }}</span>'),
    ('<span class="text-muted small">Chưa có ai dùng</span>',
     '<span class="text-muted small">{{ _(\'Chưa có ai dùng\') }}</span>'),
    ('<div class="p-4 text-center text-muted small">Chưa có mã mời nào được tạo. Hãy tạo mã mời ở form phía trên.</div>',
     '<div class="p-4 text-center text-muted small">{{ _(\'Chưa có mã mời nào được tạo. Hãy tạo mã mời ở form phía trên.\') }}</div>'),

    # Violations
    ('<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-shield-slash-fill text-danger me-2"></i>Sổ Theo Dõi & Xử Lý Vi Phạm Nội Quy</h5>',
     '<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-shield-slash-fill text-danger me-2"></i>{{ _(\'Sổ Theo Dõi & Xử Lý Vi Phạm Nội Quy\') }}</h5>'),
    ('<small class="text-muted">Ghi nhận vi phạm từ AI lọc chat realtime và báo cáo trực tiếp từ phòng học ảo.</small>',
     '<small class="text-muted">{{ _(\'Ghi nhận vi phạm từ AI lọc chat realtime và báo cáo trực tiếp từ phòng học ảo.\') }}</small>'),
    (' vụ việc</span>', ' {{ _(\'vụ việc\') }}</span>'),
    ('<th class="ps-3">Học sinh</th>', '<th class="ps-3">{{ _(\'Học sinh\') }}</th>'),
    ('<th>Trường</th>', '<th>{{ _(\'Trường\') }}</th>'),
    ('<th>Loại vi phạm</th>', '<th>{{ _(\'Loại vi phạm\') }}</th>'),
    ('<th>Mô tả chi tiết</th>', '<th>{{ _(\'Mô tả chi tiết\') }}</th>'),
    ('<th class="text-center">Mức độ</th>', '<th class="text-center">{{ _(\'Mức độ\') }}</th>'),
    ('<th>Thời gian</th>', '<th>{{ _(\'Thời gian\') }}</th>'),
    ('<th>Tình trạng TK</th>', '<th>{{ _(\'Tình trạng TK\') }}</th>'),
    ('<th class="text-end pe-3">Xử lý kỷ luật</th>', '<th class="text-end pe-3">{{ _(\'Xử lý kỷ luật\') }}</th>'),
    ('• Lớp {{ v.lop }}</small>', '• {{ _(\'Lớp\') }} {{ v.lop }}</small>'),
    ('<span class="badge bg-info-subtle text-info d-block mt-1">Phòng học #{{ v.session_id }}</span>',
     '<span class="badge bg-info-subtle text-info d-block mt-1">{{ _(\'Phòng học\') }} #{{ v.session_id }}</span>'),
    ('<span class="badge bg-warning text-dark"><i class="bi bi-bell me-1"></i>Mức 1: Nhắc nhở</span>',
     '<span class="badge bg-warning text-dark"><i class="bi bi-bell me-1"></i>{{ _(\'Mức 1: Nhắc nhở\') }}</span>'),
    ('<span class="badge bg-danger"><i class="bi bi-exclamation-triangle me-1"></i>Mức 2: Cảnh cáo</span>',
     '<span class="badge bg-danger"><i class="bi bi-exclamation-triangle me-1"></i>{{ _(\'Mức 2: Cảnh cáo\') }}</span>'),
    ('<span class="badge bg-dark text-white"><i class="bi bi-slash-circle me-1"></i>Mức 3: Đề xuất khóa</span>',
     '<span class="badge bg-dark text-white"><i class="bi bi-slash-circle me-1"></i>{{ _(\'Mức 3: Đề xuất khóa\') }}</span>'),
    ('<span class="badge bg-danger">ĐÃ KHÓA</span>',
     '<span class="badge bg-danger">{{ _(\'ĐÃ KHÓA\') }}</span>'),
    ('<span class="badge bg-warning text-dark">CHỜ QUẢN TRỊ XÁC NHẬN</span>',
     '<span class="badge bg-warning text-dark">{{ _(\'CHỜ QUẢN TRỊ XÁC NHẬN\') }}</span>'),
    ('<span class="badge bg-success">Hoạt động</span>',
     '<span class="badge bg-success">{{ _(\'Hoạt động\') }}</span>'),
    ('onsubmit="return confirm(\'CẢNH BÁO: Bạn có chắc chắn muốn XÁC NHẬN KHÓA VĨNH VIỄN tài khoản của học sinh này không?\');"',
     'onsubmit="return confirm(\'{{ _(\'CẢNH BÁO: Bạn có chắc chắn muốn XÁC NHẬN KHÓA VĨNH VIỄN tài khoản của học sinh này không?\') }}\');"'),
    ('<i class="bi bi-lock-fill me-1"></i>Xác nhận khóa thật',
     '<i class="bi bi-lock-fill me-1"></i>{{ _(\'Xác nhận khóa thật\') }}'),
    ('onclick="return confirm(\'Hủy đề xuất khóa tài khoản của học sinh này?\');"',
     'onclick="return confirm(\'{{ _(\'Hủy đề xuất khóa tài khoản của học sinh này?\') }}\');"'),
    ('Hủy đề xuất\n',
     '{{ _(\'Hủy đề xuất\') }}\n'),
    ('<span class="text-muted small"><i class="bi bi-check2-circle text-success me-1"></i>Đã xử lý khóa</span>',
     '<span class="text-muted small"><i class="bi bi-check2-circle text-success me-1"></i>{{ _(\'Đã xử lý khóa\') }}</span>'),
    ('<i class="bi bi-check2 me-1"></i>Đã nhắc nhở',
     '<i class="bi bi-check2 me-1"></i>{{ _(\'Đã nhắc nhở\') }}'),
    ('<h6 class="fw-bold">Không có vi phạm nào!</h6>',
     '<h6 class="fw-bold">{{ _(\'Không có vi phạm nào!\') }}</h6>'),
    ('<p class="small mb-0">Môi trường học tập và phòng học ảo đang duy trì văn minh, an toàn tuyệt đối.</p>',
     '<p class="small mb-0">{{ _(\'Môi trường học tập và phòng học ảo đang duy trì văn minh, an toàn tuyệt đối.\') }}</p>'),

    # Accounts List & Import
    ('<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-people-fill me-2 text-primary"></i>Danh sách Tài khoản Người dùng</h5>',
     '<h5 class="fw-bold mb-0 text-dark"><i class="bi bi-people-fill me-2 text-primary"></i>{{ _(\'Danh sách Tài khoản Người dùng\') }}</h5>'),
    ('<span class="badge bg-light text-dark border">Cập nhật theo CSDL</span>',
     '<span class="badge bg-light text-dark border">{{ _(\'Cập nhật theo CSDL\') }}</span>'),
    ('<i class="bi bi-file-earmark-arrow-up-fill me-1"></i>Nhập danh sách (Excel/CSV)',
     '<i class="bi bi-file-earmark-arrow-up-fill me-1"></i>{{ _(\'Nhập danh sách (Excel/CSV)\') }}'),
    ('Kết quả nhập danh sách gần nhất',
     '{{ _(\'Kết quả nhập danh sách gần nhất\') }}'),
    ('Đơn vị trường: <strong>',
     '{{ _(\'Đơn vị trường:\') }} <strong>'),
    ('• Đã xử lý: <strong>',
     '• {{ _(\'Đã xử lý:\') }} <strong>'),
    ('dòng</small>',
     '{{ _(\'dòng\') }}</small>'),
    ('<i class="bi bi-file-earmark-excel-fill me-1"></i>Tải file Excel kết quả (Tên đăng nhập & Mật khẩu)',
     '<i class="bi bi-file-earmark-excel-fill me-1"></i>{{ _(\'Tải file Excel kết quả (Tên đăng nhập & Mật khẩu)\') }}'),
    ('title="Đóng bảng kết quả"',
     'title="{{ _(\'Đóng bảng kết quả\') }}"'),
    ('<span class="badge bg-success px-3 py-2 fw-semibold"><i class="bi bi-person-check-fill me-1"></i>Thành công:',
     '<span class="badge bg-success px-3 py-2 fw-semibold"><i class="bi bi-person-check-fill me-1"></i>{{ _(\'Thành công:\') }}'),
    ('<span class="badge bg-danger px-3 py-2 fw-semibold"><i class="bi bi-person-x-fill me-1"></i>Lỗi / Bỏ qua:',
     '<span class="badge bg-danger px-3 py-2 fw-semibold"><i class="bi bi-person-x-fill me-1"></i>{{ _(\'Lỗi / Bỏ qua:\') }}'),
    ('<span class="fw-bold text-danger small"><i class="bi bi-exclamation-octagon me-1"></i>Chi tiết các dòng bị lỗi / bỏ qua:</span>',
     '<span class="fw-bold text-danger small"><i class="bi bi-exclamation-octagon me-1"></i>{{ _(\'Chi tiết các dòng bị lỗi / bỏ qua:\') }}</span>'),
    ('<th style="width: 70px;" class="text-center">Dòng</th>',
     '<th style="width: 70px;" class="text-center">{{ _(\'Dòng\') }}</th>'),
    ('<th>Lý do lỗi / Bỏ qua</th>',
     '<th>{{ _(\'Lý do lỗi / Bỏ qua\') }}</th>'),
    ('<th scope="col">Mã định danh</th>', '<th scope="col">{{ _(\'Mã định danh\') }}</th>'),
    ('<th scope="col">Họ và tên</th>', '<th scope="col">{{ _(\'Họ và tên\') }}</th>'),
    ('<th scope="col">Lớp / Bộ môn</th>', '<th scope="col">{{ _(\'Lớp / Bộ môn\') }}</th>'),
    ('<th scope="col">Trường học</th>', '<th scope="col">{{ _(\'Trường học\') }}</th>'),
    ('<th scope="col">Vai trò</th>', '<th scope="col">{{ _(\'Vai trò\') }}</th>'),
    ('<th scope="col">Trạng thái</th>', '<th scope="col">{{ _(\'Trạng thái\') }}</th>'),
    ('<th scope="col" class="text-end">Số dư giờ</th>', '<th scope="col" class="text-end">{{ _(\'Số dư giờ\') }}</th>'),
    ('<th scope="col">Khung giờ rảnh</th>', '<th scope="col">{{ _(\'Khung giờ rảnh\') }}</th>'),
    ('<span class="badge bg-danger">Tổng Quản trị</span>',
     '<span class="badge bg-danger">{{ _(\'Tổng Quản trị\') }}</span>'),
    ('<span class="badge bg-warning text-dark">Quản trị trường</span>',
     '<span class="badge bg-warning text-dark">{{ _(\'Quản trị trường\') }}</span>'),
    ('<span class="badge bg-primary">Giáo viên</span>',
     '<span class="badge bg-primary">{{ _(\'Giáo viên\') }}</span>'),
    ('<span class="badge bg-success">Học sinh</span>',
     '<span class="badge bg-success">{{ _(\'Học sinh\') }}</span>'),
    ('<span class="badge bg-danger">Đã khóa</span>',
     '<span class="badge bg-danger">{{ _(\'Đã khóa\') }}</span>'),
    ('<span class="badge bg-warning text-dark">Đề xuất khóa</span>',
     '<span class="badge bg-warning text-dark">{{ _(\'Đề xuất khóa\') }}</span>'),
    ('<span class="badge bg-secondary">Chờ duyệt</span>',
     '<span class="badge bg-secondary">{{ _(\'Chờ duyệt\') }}</span>'),
    ('<span class="badge bg-success-subtle text-success">Hoạt động</span>',
     '<span class="badge bg-success-subtle text-success">{{ _(\'Hoạt động\') }}</span>'),

    # Community pending skills
    ('<i class="bi bi-globe2 text-warning me-2"></i>Kỹ Năng Chờ Duyệt Lên Cộng Đồng Liên Trường',
     '<i class="bi bi-globe2 text-warning me-2"></i>{{ _(\'Kỹ Năng Chờ Duyệt Lên Cộng Đồng Liên Trường\') }}'),
    ('Tổng quản trị hoặc Quản trị viên bất kỳ trường nào đều có quyền duyệt. Một người duyệt là đủ; hệ thống tự động ghi nhận nhật ký người duyệt.',
     '{{ _(\'Tổng quản trị hoặc Quản trị viên bất kỳ trường nào đều có quyền duyệt. Một người duyệt là đủ; hệ thống tự động ghi nhận nhật ký người duyệt.\') }}'),
    ('yêu cầu chờ duyệt\n',
     '{{ _(\'yêu cầu chờ duyệt\') }}\n'),
    ('<th>Kỹ năng đề xuất</th>', '<th>{{ _(\'Kỹ năng đề xuất\') }}</th>'),
    ('<th>Học sinh đăng ký</th>', '<th>{{ _(\'Học sinh đăng ký\') }}</th>'),
    ('<th class="text-center">Giờ dạy thật</th>', '<th class="text-center">{{ _(\'Giờ dạy thật\') }}</th>'),
    ('<th class="text-end">Hành động duyệt</th>', '<th class="text-end">{{ _(\'Hành động duyệt\') }}</th>'),
    ('<i class="bi bi-check-lg me-1"></i>Duyệt lên Liên trường',
     '<i class="bi bi-check-lg me-1"></i>{{ _(\'Duyệt lên Liên trường\') }}'),
    ('<h6 class="fw-bold text-dark">Hiện không có kỹ năng nào chờ duyệt lên Cộng đồng liên trường</h6>',
     '<h6 class="fw-bold text-dark">{{ _(\'Hiện không có kỹ năng nào chờ duyệt lên Cộng đồng liên trường\') }}</h6>'),
    ('<p class="small mb-0">Tất cả yêu cầu đăng kỹ năng liên trường đã được xử lý hoàn tất.</p>',
     '<p class="small mb-0">{{ _(\'Tất cả yêu cầu đăng kỹ năng liên trường đã được xử lý hoàn tất.\') }}</p>'),

    # Active community skills
    ('<i class="bi bi-clock-history text-primary me-2"></i>Kỹ Năng Đang Hoạt Động Trên Cộng Đồng Liên Trường',
     '<i class="bi bi-clock-history text-primary me-2"></i>{{ _(\'Kỹ Năng Đang Hoạt Động Trên Cộng Đồng Liên Trường\') }}'),
    ('<small class="text-muted">Nhật ký các kỹ năng đã được quản trị viên phê duyệt</small>',
     '<small class="text-muted">{{ _(\'Nhật ký các kỹ năng đã được quản trị viên phê duyệt\') }}</small>'),
    ('<th>Kỹ năng</th>', '<th>{{ _(\'Kỹ năng\') }}</th>'),
    ('<th>Chủ kỹ năng</th>', '<th>{{ _(\'Chủ kỹ năng\') }}</th>'),
    ('<th>Người phê duyệt</th>', '<th>{{ _(\'Người phê duyệt\') }}</th>'),
    ('<th>Thời gian duyệt</th>', '<th>{{ _(\'Thời gian duyệt\') }}</th>'),
    ('<i class="bi bi-person-check me-1"></i>{{ sk.nguoi_duyet_ten if sk.nguoi_duyet_ten else \'Quản trị viên\' }}',
     '<i class="bi bi-person-check me-1"></i>{{ sk.nguoi_duyet_ten if sk.nguoi_duyet_ten else _(\'Quản trị viên\') }}'),

    # Community tasks
    ('<i class="bi bi-heart-fill text-danger me-2"></i>Thêm Chương Trình Giờ Công Ích Mới',
     '<i class="bi bi-heart-fill text-danger me-2"></i>{{ _(\'Thêm Chương Trình Giờ Công Ích Mới\') }}'),
    ('<p class="text-muted small mb-0">Quản trị viên chủ động phát động các chương trình thiện nguyện, lao động công ích, hỗ trợ thư viện để học sinh cống hiến và nhận giờ tín dụng.</p>',
     '<p class="text-muted small mb-0">{{ _(\'Quản trị viên chủ động phát động các chương trình thiện nguyện, lao động công ích, hỗ trợ thư viện để học sinh cống hiến và nhận giờ tín dụng.\') }}</p>'),
    ('<i class="bi bi-people-fill me-1"></i> Giờ Công Ích Học Đường',
     '<i class="bi bi-people-fill me-1"></i> {{ _(\'Giờ Công Ích Học Đường\') }}'),
    ('<label class="form-label small fw-semibold">Tên chương trình cộng đồng <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Tên chương trình cộng đồng\') }} <span class="text-danger">*</span></label>'),
    ('placeholder="Ví dụ: Trồng cây xanh khuôn viên trường, Thăm mái ấm..."',
     'placeholder="{{ _(\'Ví dụ: Trồng cây xanh khuôn viên trường, Thăm mái ấm...\') }}"'),
    ('<label class="form-label small fw-semibold">Số giờ thưởng (*) <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Số giờ thưởng (*)\') }} <span class="text-danger">*</span></label>'),
    ('<span class="input-group-text bg-light">giờ (h)</span>',
     '<span class="input-group-text bg-light">{{ _(\'giờ (h)\') }}</span>'),
    ('<label class="form-label small fw-semibold">Trạng thái <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Trạng thái\') }} <span class="text-danger">*</span></label>'),
    ('<option value="sap_dien_ra">Sắp diễn ra</option>',
     '<option value="sap_dien_ra">{{ _(\'Sắp diễn ra\') }}</option>'),
    ('<option value="dang_dien_ra" selected>Đang diễn ra</option>',
     '<option value="dang_dien_ra" selected>{{ _(\'Đang diễn ra\') }}</option>'),
    ('<option value="da_ket_thuc">Đã kết thúc</option>',
     '<option value="da_ket_thuc">{{ _(\'Đã kết thúc\') }}</option>'),
    ('<label class="form-label small fw-semibold">Ngày bắt đầu</label>',
     '<label class="form-label small fw-semibold">{{ _(\'Ngày bắt đầu\') }}</label>'),
    ('<label class="form-label small fw-semibold">Ngày kết thúc</label>',
     '<label class="form-label small fw-semibold">{{ _(\'Ngày kết thúc\') }}</label>'),
    ('<label class="form-label small fw-semibold">Mô tả chi tiết chương trình</label>',
     '<label class="form-label small fw-semibold">{{ _(\'Mô tả chi tiết chương trình\') }}</label>'),
    ('placeholder="Nội dung công việc, kế hoạch tổ chức, ý nghĩa cộng đồng..."',
     'placeholder="{{ _(\'Nội dung công việc, kế hoạch tổ chức, ý nghĩa cộng đồng...\') }}"'),
    ('<i class="bi bi-plus-circle me-1"></i> Lưu & Phát động chương trình',
     '<i class="bi bi-plus-circle me-1"></i> {{ _(\'Lưu & Phát động chương trình\') }}'),
    ('<i class="bi bi-card-checklist text-primary me-2"></i>Danh Sách Chương Trình Giờ Công Ích Học Đường',
     '<i class="bi bi-card-checklist text-primary me-2"></i>{{ _(\'Danh Sách Chương Trình Giờ Công Ích Học Đường\') }}'),
    ('<small class="text-muted">Quản trị viên có thể theo dõi số lượng đăng ký, chỉnh sửa thông tin hoặc kết thúc chương trình.</small>',
     '<small class="text-muted">{{ _(\'Quản trị viên có thể theo dõi số lượng đăng ký, chỉnh sửa thông tin hoặc kết thúc chương trình.\') }}</small>'),
    ('chương trình</span>', '{{ _(\'chương trình\') }}</span>'),
    ('<th>Tên chương trình & Mô tả</th>', '<th>{{ _(\'Tên chương trình & Mô tả\') }}</th>'),
    ('<th style="width: 120px;">Số giờ thưởng</th>', '<th style="width: 120px;">{{ _(\'Số giờ thưởng\') }}</th>'),
    ('<th>Thời gian bắt đầu / kết thúc</th>', '<th>{{ _(\'Thời gian bắt đầu / kết thúc\') }}</th>'),
    ('<th style="width: 120px;">Học sinh đăng ký</th>', '<th style="width: 120px;">{{ _(\'Học sinh đăng ký\') }}</th>'),
    ('<th style="width: 160px;" class="text-end">Hành động</th>', '<th style="width: 160px;" class="text-end">{{ _(\'Hành động\') }}</th>'),
    ('Hạn: {{ task.han_dang_ky or \'Không giới hạn\' }}',
     '{{ _(\'Hạn:\') }} {{ task.han_dang_ky or _(\'Không giới hạn\') }}'),
    ('<span class="badge bg-primary"><i class="bi bi-play-circle me-1"></i>Đang diễn ra</span>',
     '<span class="badge bg-primary"><i class="bi bi-play-circle me-1"></i>{{ _(\'Đang diễn ra\') }}</span>'),
    ('<span class="badge bg-warning text-dark"><i class="bi bi-hourglass me-1"></i>Sắp diễn ra</span>',
     '<span class="badge bg-warning text-dark"><i class="bi bi-hourglass me-1"></i>{{ _(\'Sắp diễn ra\') }}</span>'),
    ('<span class="badge bg-secondary"><i class="bi bi-check-circle me-1"></i>Đã kết thúc</span>',
     '<span class="badge bg-secondary"><i class="bi bi-check-circle me-1"></i>{{ _(\'Đã kết thúc\') }}</span>'),
    ('bạn</span>', '{{ _(\'bạn\') }}</span>'),
    ('title="Điểm danh học sinh tham gia"', 'title="{{ _(\'Điểm danh học sinh tham gia\') }}"'),
    ('<i class="bi bi-card-checklist me-1"></i>Điểm danh',
     '<i class="bi bi-card-checklist me-1"></i>{{ _(\'Điểm danh\') }}'),
    ('title="Chỉnh sửa thông tin"', 'title="{{ _(\'Chỉnh sửa thông tin\') }}"'),
    ('title="Xóa chương trình này"', 'title="{{ _(\'Xóa chương trình này\') }}"'),
    ('onclick="return confirm(\'Bạn có chắc chắn muốn xóa chương trình này?\');"',
     'onclick="return confirm(\'{{ _(\'Bạn có chắc chắn muốn xóa chương trình này?\') }}\');"'),
    ('<h6 class="fw-bold">Chưa có chương trình nào</h6>',
     '<h6 class="fw-bold">{{ _(\'Chưa có chương trình nào\') }}</h6>'),
    ('<p class="small mb-0">Hãy tạo chương trình vì cộng đồng đầu tiên ở form bên trên để học sinh tham gia.</p>',
     '<p class="small mb-0">{{ _(\'Hãy tạo chương trình vì cộng đồng đầu tiên ở form bên trên để học sinh tham gia.\') }}</p>'),

    # School management
    ('<i class="bi bi-building-add text-primary me-2"></i>Thêm Trường Học Mới',
     '<i class="bi bi-building-add text-primary me-2"></i>{{ _(\'Thêm Trường Học Mới\') }}'),
    ('<p class="text-muted small mb-0">Hệ sinh thái mở rộng — Tổng Quản trị viên khởi tạo không gian trường học độc lập mới.</p>',
     '<p class="text-muted small mb-0">{{ _(\'Hệ sinh thái mở rộng — Tổng Quản trị viên khởi tạo không gian trường học độc lập mới.\') }}</p>'),
    ('placeholder="vd: Trường THPT Chuyên Hạ Long"',
     'placeholder="{{ _(\'vd: Trường THPT Chuyên Hạ Long\') }}"'),
    ('<option value="chuan_bi_trien_khai" selected>Chuẩn bị triển khai</option>',
     '<option value="chuan_bi_trien_khai" selected>{{ _(\'Chuẩn bị triển khai\') }}</option>'),
    ('<option value="dang_thi_diem">Đang thí điểm</option>',
     '<option value="dang_thi_diem">{{ _(\'Đang thí điểm\') }}</option>'),
    ('<option value="dang_hoat_dong">Đang hoạt động</option>',
     '<option value="dang_hoat_dong">{{ _(\'Đang hoạt động\') }}</option>'),
    ('<small class="text-muted">Tùy chọn tải ảnh Logo ngay hoặc cập nhật sau.</small>',
     '<small class="text-muted">{{ _(\'Tùy chọn tải ảnh Logo ngay hoặc cập nhật sau.\') }}</small>'),
    ('<i class="bi bi-plus-circle me-1"></i> Khởi tạo Trường Học',
     '<i class="bi bi-plus-circle me-1"></i> {{ _(\'Khởi tạo Trường Học\') }}'),
    ('<i class="bi bi-buildings text-primary me-2"></i>Danh Sách Các Trường Học Trong Hệ Thống',
     '<i class="bi bi-buildings text-primary me-2"></i>{{ _(\'Danh Sách Các Trường Học Trong Hệ Thống\') }}'),
    ('<small class="text-muted">Quản trị viên có thể theo dõi trạng thái, sửa đổi thông tin hoặc ẩn/hiện trường học.</small>',
     '<small class="text-muted">{{ _(\'Quản trị viên có thể theo dõi trạng thái, sửa đổi thông tin hoặc ẩn/hiện trường học.\') }}</small>'),
    ('trường</span>', '{{ _(\'trường\') }}</span>'),
    ('<th>Logo & Tên trường</th>', '<th>{{ _(\'Logo & Tên trường\') }}</th>'),
    ('<th>Mã trường</th>', '<th>{{ _(\'Mã trường\') }}</th>'),
    ('<th>Học sinh</th>', '<th>{{ _(\'Học sinh\') }}</th>'),
    ('<th>Giáo viên</th>', '<th>{{ _(\'Giáo viên\') }}</th>'),
    ('<th>Thao tác</th>', '<th>{{ _(\'Thao tác\') }}</th>'),
    ('<i class="bi bi-broadcast me-1"></i>Đang thí điểm',
     '<i class="bi bi-broadcast me-1"></i>{{ _(\'Đang thí điểm\') }}'),
    ('<i class="bi bi-check-circle-fill me-1"></i>Đang hoạt động',
     '<i class="bi bi-check-circle-fill me-1"></i>{{ _(\'Đang hoạt động\') }}'),
    ('<i class="bi bi-hourglass-split me-1"></i>Chuẩn bị triển khai',
     '<i class="bi bi-hourglass-split me-1"></i>{{ _(\'Chuẩn bị triển khai\') }}'),
    ('<i class="bi bi-pause-circle-fill me-1"></i>Tạm ngưng',
     '<i class="bi bi-pause-circle-fill me-1"></i>{{ _(\'Tạm ngưng\') }}'),
    ('<i class="bi bi-eye-slash-fill me-1"></i>Đã ẩn',
     '<i class="bi bi-eye-slash-fill me-1"></i>{{ _(\'Đã ẩn\') }}'),
    ('<i class="bi bi-shield-lock-fill me-1"></i>Cố định (Không sửa/xóa)',
     '<i class="bi bi-shield-lock-fill me-1"></i>{{ _(\'Cố định (Không sửa/xóa)\') }}'),
    ('title="Sửa tên / logo / trạng thái"', 'title="{{ _(\'Sửa tên / logo / trạng thái\') }}"'),
    ('<i class="bi bi-pencil-square me-1"></i>Sửa',
     '<i class="bi bi-pencil-square me-1"></i>{{ _(\'Sửa\') }}'),
    ('title="Hiện lại trường trên hệ thống"', 'title="{{ _(\'Hiện lại trường trên hệ thống\') }}"'),
    ('<i class="bi bi-eye me-1"></i>Hiện lại',
     '<i class="bi bi-eye me-1"></i>{{ _(\'Hiện lại\') }}'),
    ('title="Ẩn trường (không xóa)"', 'title="{{ _(\'Ẩn trường (không xóa)\') }}"'),
    ('<i class="bi bi-eye-slash me-1"></i>Ẩn trường',
     '<i class="bi bi-eye-slash me-1"></i>{{ _(\'Ẩn trường\') }}'),

    # Google Drive 5TB storage panel
    ('<i class="bi bi-google text-danger me-2"></i>Kho Lưu Trữ Đám Mây Google Drive 5TB Toàn Hệ Thống',
     '<i class="bi bi-google text-danger me-2"></i>{{ _(\'Kho Lưu Trữ Đám Mây Google Drive 5TB Toàn Hệ Thống\') }}'),
    ('Tài khoản Google Drive 5TB của Thầy phụ trách chung toàn hệ thống — Tự động phân cấp thư mục theo trường và môn học.',
     '{{ _(\'Tài khoản Google Drive 5TB của Thầy phụ trách chung toàn hệ thống — Tự động phân cấp thư mục theo trường và môn học.\') }}'),
    ('<i class="bi bi-check-circle-fill me-1"></i> Google Drive: Đã Kết Nối (OAuth2)',
     '<i class="bi bi-check-circle-fill me-1"></i> {{ _(\'Google Drive: Đã Kết Nối (OAuth2)\') }}'),
    ('<i class="bi bi-exclamation-triangle-fill me-1"></i> Chế độ Fallback / Chưa nạp Token',
     '<i class="bi bi-exclamation-triangle-fill me-1"></i> {{ _(\'Chế độ Fallback / Chưa nạp Token\') }}'),
    ('<i class="bi bi-key-fill text-primary me-2"></i>Xác thực OAuth2 & Biến Môi Trường (Render)',
     '<i class="bi bi-key-fill text-primary me-2"></i>{{ _(\'Xác thực OAuth2 & Biến Môi Trường (Render)\') }}'),
    ('Nhấn nút bên dưới để đăng nhập bằng tài khoản Google Drive 5TB của Thầy. Sau khi cấp quyền 1 lần duy nhất, mã Refresh Token sẽ được cấp để lưu vào <code>GOOGLE_REFRESH_TOKEN</code> trên Dashboard Render.',
     '{{ _(\'Nhấn nút bên dưới để đăng nhập bằng tài khoản Google Drive 5TB của Thầy. Sau khi cấp quyền 1 lần duy nhất, mã Refresh Token sẽ được cấp để lưu vào GOOGLE_REFRESH_TOKEN trên Dashboard Render.\') }}'),
    ('<strong>TUYỆT ĐỐI BẢO MẬT:</strong> Refresh token và Client Secret không bao giờ được hardcode trong mã nguồn hoặc commit lên GitHub. Mọi xác thực đều được đọc trực tiếp từ biến môi trường của máy chủ Render.',
     '<strong>{{ _(\'TUYỆT ĐỐI BẢO MẬT:\') }}</strong> {{ _(\'Refresh token và Client Secret không bao giờ được hardcode trong mã nguồn hoặc commit lên GitHub. Mọi xác thực đều được đọc trực tiếp từ biến môi trường của máy chủ Render.\') }}'),
    ('<i class="bi bi-google me-2"></i>Kết Nối Google Drive (OAuth2)',
     '<i class="bi bi-google me-2"></i>{{ _(\'Kết Nối Google Drive (OAuth2)\') }}'),
    ('<i class="bi bi-folder2-open me-1"></i>Xem Kho Tài Liệu',
     '<i class="bi bi-folder2-open me-1"></i>{{ _(\'Xem Kho Tài Liệu\') }}'),
    ('<i class="bi bi-diagram-3-fill text-success me-2"></i>Cấu Trúc Thư Mục Tự Động',
     '<i class="bi bi-diagram-3-fill text-success me-2"></i>{{ _(\'Cấu Trúc Thư Mục Tự Động\') }}'),
    ('<p class="small text-muted mb-2">Hệ thống tự động khởi tạo cấu trúc thư mục phân cấp trên Google Drive:</p>',
     '<p class="small text-muted mb-2">{{ _(\'Hệ thống tự động khởi tạo cấu trúc thư mục phân cấp trên Google Drive:\') }}</p>'),
    ('<li>Dung lượng tối đa: <strong>500MB/tệp</strong>.</li>',
     '<li>{{ _(\'Dung lượng tối đa:\') }} <strong>500MB/{{ _(\'tệp\') }}</strong>.</li>'),
    ('<li>Stream tải lên & tải về trực tiếp từ Drive (không lưu trên đĩa Render).</li>',
     '<li>{{ _(\'Stream tải lên & tải về trực tiếp từ Drive (không lưu trên đĩa Render).\') }}</li>'),
    ('<li>Học sinh chỉ xem & tải tài liệu của trường mình.</li>',
     '<li>{{ _(\'Học sinh chỉ xem & tải tài liệu của trường mình.\') }}</li>'),

    # Modals
    ('<h5 class="modal-title fw-bold text-dark"><i class="bi bi-image me-2 text-primary"></i>Tải Logo Thật cho Trường học</h5>',
     '<h5 class="modal-title fw-bold text-dark"><i class="bi bi-image me-2 text-primary"></i>{{ _(\'Tải Logo Thật cho Trường học\') }}</h5>'),
    ('<label class="form-label small fw-semibold">Chọn trường học <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Chọn trường học\') }} <span class="text-danger">*</span></label>'),
    ('<label class="form-label small fw-semibold">Trường học</label>',
     '<label class="form-label small fw-semibold">{{ _(\'Trường học\') }}</label>'),
    ('<label class="form-label small fw-semibold">Chọn file ảnh Logo thật <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Chọn file ảnh Logo thật\') }} <span class="text-danger">*</span></label>'),
    ('<small class="text-muted">Định dạng hỗ trợ: PNG, JPG, WEBP. Ảnh sẽ được cập nhật hiển thị tại thẻ trường học.</small>',
     '<small class="text-muted">{{ _(\'Định dạng hỗ trợ: PNG, JPG, WEBP. Ảnh sẽ được cập nhật hiển thị tại thẻ trường học.\') }}</small>'),
    ('<button type="button" class="btn btn-light rounded-pill px-4" data-bs-dismiss="modal">Đóng</button>',
     '<button type="button" class="btn btn-light rounded-pill px-4" data-bs-dismiss="modal">{{ _(\'Đóng\') }}</button>'),
    ('<i class="bi bi-cloud-arrow-up-fill me-1"></i> Tải lên Logo',
     '<i class="bi bi-cloud-arrow-up-fill me-1"></i> {{ _(\'Tải lên Logo\') }}'),

    ('<i class="bi bi-pencil-square me-2 text-primary"></i>Sửa Thông Tin Trường #{{ s.id }}',
     '<i class="bi bi-pencil-square me-2 text-primary"></i>{{ _(\'Sửa Thông Tin Trường\') }} #{{ s.id }}'),
    ('<label class="form-label small fw-semibold">Tên trường học <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Tên trường học\') }} <span class="text-danger">*</span></label>'),
    ('<label class="form-label small fw-semibold">Trạng thái hoạt động <span class="text-danger">*</span></label>',
     '<label class="form-label small fw-semibold">{{ _(\'Trạng thái hoạt động\') }} <span class="text-danger">*</span></label>'),
    ('<option value="chuan_bi_trien_khai" {% if s.trang_thai == \'chuan_bi_trien_khai\' %}selected{% endif %}>Chuẩn bị triển khai</option>',
     '<option value="chuan_bi_trien_khai" {% if s.trang_thai == \'chuan_bi_trien_khai\' %}selected{% endif %}>{{ _(\'Chuẩn bị triển khai\') }}</option>'),
    ('<option value="dang_thi_diem" {% if s.trang_thai == \'dang_thi_diem\' %}selected{% endif %}>Đang thí điểm</option>',
     '<option value="dang_thi_diem" {% if s.trang_thai == \'dang_thi_diem\' %}selected{% endif %}>{{ _(\'Đang thí điểm\') }}</option>'),
    ('<option value="dang_hoat_dong" {% if s.trang_thai in (\'dang_su_dung\', \'dang_hoat_dong\') %}selected{% endif %}>Đang hoạt động</option>',
     '<option value="dang_hoat_dong" {% if s.trang_thai in (\'dang_su_dung\', \'dang_hoat_dong\') %}selected{% endif %}>{{ _(\'Đang hoạt động\') }}</option>'),
    ('<option value="tam_ngung" {% if s.trang_thai in (\'vo_hieu_hoa\', \'tam_ngung\') %}selected{% endif %}>Tạm ngưng</option>',
     '<option value="tam_ngung" {% if s.trang_thai in (\'vo_hieu_hoa\', \'tam_ngung\') %}selected{% endif %}>{{ _(\'Tạm ngưng\') }}</option>'),
    ('<label class="form-label small fw-semibold">Logo trường học</label>',
     '<label class="form-label small fw-semibold">{{ _(\'Logo trường học\') }}</label>'),
    ('<small class="text-muted">Để trống nếu không muốn đổi ảnh logo.</small>',
     '<small class="text-muted">{{ _(\'Để trống nếu không muốn đổi ảnh logo.\') }}</small>'),
    ('<button type="button" class="btn btn-light rounded-pill px-4" data-bs-dismiss="modal">Hủy</button>',
     '<button type="button" class="btn btn-light rounded-pill px-4" data-bs-dismiss="modal">{{ _(\'Hủy\') }}</button>'),
    ('<i class="bi bi-save me-1"></i> Lưu thay đổi',
     '<i class="bi bi-save me-1"></i> {{ _(\'Lưu thay đổi\') }}'),

    # Bulk Import Modal
    ('<h5 class="modal-title fw-bold text-dark mb-0" id="modalImportUsersLabel">Nhập Danh Sách Tài Khoản Hàng Loạt</h5>',
     '<h5 class="modal-title fw-bold text-dark mb-0" id="modalImportUsersLabel">{{ _(\'Nhập Danh Sách Tài Khoản Hàng Loạt\') }}</h5>'),
    ('<small class="text-muted">Tạo nhanh tài khoản Quản trị trường, Giáo viên và Học sinh từ file Excel/CSV</small>',
     '<small class="text-muted">{{ _(\'Tạo nhanh tài khoản Quản trị trường, Giáo viên và Học sinh từ file Excel/CSV\') }}</small>'),
    ('<span class="fw-bold text-dark d-block mb-1"><i class="bi bi-file-earmark-excel me-1 text-warning"></i>Tải file mẫu chuẩn định dạng</span>',
     '<span class="fw-bold text-dark d-block mb-1"><i class="bi bi-file-earmark-excel me-1 text-warning"></i>{{ _(\'Tải file mẫu chuẩn định dạng\') }}</span>'),
    ('Cột mẫu: <code>họ_tên</code> | <code>vai_trò</code> (quantruong/giaovien/hocsinh) | <code>lớp</code> | <code>email</code> | <code>số_điện_thoại</code> | <code>ghi_chú</code>',
     '{{ _(\'Cột mẫu: họ_tên | vai_trò (quantruong/giaovien/hocsinh) | lớp | email | số_điện_thoại | ghi_chú\') }}'),
    ('<i class="bi bi-download me-1"></i>Tải file Excel mẫu',
     '<i class="bi bi-download me-1"></i>{{ _(\'Tải file Excel mẫu\') }}'),
    ('<label class="form-label fw-semibold small text-dark">Chọn trường học áp dụng <span class="text-danger">*</span></label>',
     '<label class="form-label fw-semibold small text-dark">{{ _(\'Chọn trường học áp dụng\') }} <span class="text-danger">*</span></label>'),
    ('<small class="text-muted">Tổng quản trị (Super Admin) có quyền chỉ định trường nhận danh sách tài khoản.</small>',
     '<small class="text-muted">{{ _(\'Tổng quản trị (Super Admin) có quyền chỉ định trường nhận danh sách tài khoản.\') }}</small>'),
    ('<label class="form-label fw-semibold small text-dark">Đơn vị trường học</label>',
     '<label class="form-label fw-semibold small text-dark">{{ _(\'Đơn vị trường học\') }}</label>'),
    ('<span class="badge bg-primary-subtle text-primary ms-auto">Trường của bạn</span>',
     '<span class="badge bg-primary-subtle text-primary ms-auto">{{ _(\'Trường của bạn\') }}</span>'),
    ('<label class="form-label fw-semibold small text-dark">Chọn file Excel (.xlsx) hoặc CSV (.csv) <span class="text-danger">*</span></label>',
     '<label class="form-label fw-semibold small text-dark">{{ _(\'Chọn file Excel (.xlsx) hoặc CSV (.csv)\') }} <span class="text-danger">*</span></label>'),
    ('<small class="text-muted">Hỗ trợ các định dạng bảng tính thông dụng (.xlsx, .csv định dạng UTF-8).</small>',
     '<small class="text-muted">{{ _(\'Hỗ trợ các định dạng bảng tính thông dụng (.xlsx, .csv định dạng UTF-8).\') }}</small>'),
    ('<div class="fw-bold mb-1"><i class="bi bi-shield-check me-1"></i>Cơ chế bảo mật & Tự động hóa hệ thống:</div>',
     '<div class="fw-bold mb-1"><i class="bi bi-shield-check me-1"></i>{{ _(\'Cơ chế bảo mật & Tự động hóa hệ thống:\') }}</div>'),
    ('<li><strong>Tên đăng nhập & Mật khẩu riêng:</strong> Hệ thống tự sinh mã đăng nhập duy nhất và mật khẩu ngẫu nhiên riêng cho từng người (không dùng chung mật khẩu mặc định).</li>',
     '<li><strong>{{ _(\'Tên đăng nhập & Mật khẩu riêng:\') }}</strong> {{ _(\'Hệ thống tự sinh mã đăng nhập duy nhất và mật khẩu ngẫu nhiên riêng cho từng người (không dùng chung mật khẩu mặc định).\') }}</li>'),
    ('<li><strong>Mật khẩu băm an toàn:</strong> Mật khẩu được mã hóa một chiều bằng Werkzeug trước khi lưu CSDL.</li>',
     '<li><strong>{{ _(\'Mật khẩu băm an toàn:\') }}</strong> {{ _(\'Mật khẩu được mã hóa một chiều bằng Werkzeug trước khi lưu CSDL.\') }}</li>'),
    ('<li><strong>Trạng thái hoạt động:</strong> Tài khoản được kích hoạt ngay, học sinh tự động nhận +2.0 giờ ban đầu.</li>',
     '<li><strong>{{ _(\'Trạng thái hoạt động:\') }}</strong> {{ _(\'Tài khoản được kích hoạt ngay, học sinh tự động nhận +2.0 giờ ban đầu.\') }}</li>'),
    ('<li><strong>Bỏ qua dòng lỗi:</strong> Dòng sai sót sẽ được bỏ qua và ghi rõ lý do, không chặn các dòng đúng.</li>',
     '<li><strong>{{ _(\'Bỏ qua dòng lỗi:\') }}</strong> {{ _(\'Dòng sai sót sẽ được bỏ qua và ghi rõ lý do, không chặn các dòng đúng.\') }}</li>'),
    ('<li><strong>Xuất file kết quả:</strong> Ngay sau khi nhập, bạn có thể tải file Excel kết quả chứa thông tin đăng nhập để bàn giao cho từng cá nhân.</li>',
     '<li><strong>{{ _(\'Xuất file kết quả:\') }}</strong> {{ _(\'Ngay sau khi nhập, bạn có thể tải file Excel kết quả chứa thông tin đăng nhập để bàn giao cho từng cá nhân.\') }}</li>'),
    ('<i class="bi bi-upload me-1"></i> Bắt đầu Nhập danh sách',
     '<i class="bi bi-upload me-1"></i> {{ _(\'Bắt đầu Nhập danh sách\') }}'),

    # JS
    ("lbl.textContent = 'Số lượng mã lớp';",
     "lbl.textContent = '{{ _(\\'Số lượng mã lớp\\') }}';"),
    ("lbl.textContent = 'Số lượng mã cá nhân';",
     "lbl.textContent = '{{ _(\\'Số lượng mã cá nhân\\') }}';"),
]

count = 0
for src, dst in replacements:
    if src in content:
        content = content.replace(src, dst)
        count += 1
    else:
        print(f"Warning: pattern not found: {src[:50]}")

with open('templates/admin.html', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Applied {count}/{len(replacements)} replacements to templates/admin.html")
